<a href="https://colab.research.google.com/github/abhinavmishra786429/dl-practice/blob/main/gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
% matplotlib inline
import tensorflow as tf
from tensorflow  import keras

In [2]:
from google.colab import files

uploaded = files.upload()

Saving age.csv to age.csv


In [3]:


for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

User uploaded file "age.csv" with length 244 bytes


In [7]:
df = pd.read_csv("age.csv")

In [9]:
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1

In [10]:
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size = 0.2,random_state=25)

In [17]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age']/100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age']/100

In [18]:
model = keras.Sequential([
             keras.layers.Dense(1,input_shape = (2,),activation='sigmoid',kernel_initializer = 'ones',bias_initializer='zeros')             

])

model.compile(
    optimizer = 'adam',
    loss  ='binary_crossentropy',
    metrics = ['accuracy']
)

model.fit(X_train_scaled,y_train,epochs = 5000)

Streaming output truncated to the last 5000 lines.
Epoch 2501/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.4618 - accuracy: 0.8000
Epoch 2502/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.4617 - accuracy: 0.8000
Epoch 2503/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.4617 - accuracy: 0.8000
Epoch 2504/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.4617 - accuracy: 0.8000
Epoch 2505/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.4616 - accuracy: 0.8000
Epoch 2506/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.4616 - accuracy: 0.8000
Epoch 2507/5000
1/1 [==============================] - 0s 21ms/step - loss: 0.4615 - accuracy: 0.8000
Epoch 2508/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.4615 - accuracy: 0.8000
Epoch 2509/5000
1/1 [==============================] - 0s 6ms/step - loss: 0.4615 - accuracy: 0.8000
Epoch 2510/5000
1/1 [==================

In [19]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 0s 117ms/step - loss: 0.3576 - accuracy: 0.8333


[0.35758814215660095, 0.8333333134651184]

In [20]:
model.predict(X_test_scaled)

array([[0.8079233 ],
       [0.445225  ],
       [0.15217522],
       [0.586919  ],
       [0.8250319 ],
       [0.90346134]], dtype=float32)

In [21]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

In [22]:
coef,intercept = model.get_weights()

In [23]:
coef,intercept

(array([[5.7122607],
        [1.9546393]], dtype=float32), array([-3.2028291], dtype=float32))

In [24]:
import math
def sigmoid(x):
  return 1/(1+math.exp(-x))

In [25]:
sigmoid(18)

0.9999999847700205

In [26]:
sigmoid(19)

0.9999999943972036

In [27]:
sigmoid(20)

0.9999999979388463

In [28]:
sigmoid(21)

0.9999999992417439

In [29]:
sigmoid(22)

0.9999999997210531

In [30]:
sigmoid(23)

0.9999999998973812

In [31]:
sigmoid(25)

0.999999999986112

In [32]:
def prediction_function(age,affordibility):
  weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
  return sigmoid(weighted_sum)

In [33]:
prediction_function(0.47,1)

0.8079233672404202

In [34]:
prediction_function(0.18,1)

0.44522499785293973

In [35]:
def sigmoid_numpy(x):
  return 1/(1+np.exp(-x))

In [36]:
sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [39]:
def log_loss(y_true,y_predicted):
  epsilon  =1e-15
  y_predicted_new = [max(i,epsilon) for i in y_predicted]
  y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
  y_predicted_new =np.array(y_predicted_new)
  return -np.mean(y_true*np.log(y_predicted_new) + (1- y_true)*np.log(1-y_predicted_new))

In [40]:
def gradient_descent(age,affordibility,y_true,epochs,loss_thresold):

  w1 = w2 = 1
  bias = 0
  rate = 0.5
  n = len(age)
  for i in range(epochs):
    weighted_sum = w1*age +w2*affordibility +bias
    y_predicted= sigmoid_numpy(weighted_sum)
    loss = log_loss(y_true, y_predicted)

    w1d = (1/n)*np.dot(np.transpose(age),(y_predicted - y_true))
    w2d = (1/n)*np.dot(np.transpose(affordibility),(y_predicted - y_true))
    biased = np.mean(y_predicted - y_true)

    w1  =w1 - rate*w1d
    w2 = w2 - rate*w2d
    bias = bias - rate*biased

    print(f'Epoch:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')
    if loss<=loss_thresold:
      break
      return w1 ,w2, bias
      

In [45]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,1000,0.4631)

Epoch:0,w1:0.9861804793792851,w2:0.9828167191603727,bias:-0.08512676387366358,loss:0.6247119326497158
Epoch:1,w1:0.9761843421497219,w2:0.9708322170253466,bias:-0.1606856974027985,loss:0.6101959557010146
Epoch:2,w1:0.9696130175647895,w2:0.963521483488867,bias:-0.22768726276266818,loss:0.5990231995835918
Epoch:3,w1:0.9660602138351069,w2:0.9603222822992482,bias:-0.28714898774023845,loss:0.5904041973219015
Epoch:4,w1:0.965132778775779,w2:0.9606725574243884,bias:-0.3400469223612719,loss:0.5836967400366617
Epoch:5,w1:0.9664645313782291,w2:0.9640369944609515,bias:-0.3872843100846284,loss:0.5783981558023443
Epoch:6,w1:0.9697240239001185,w2:0.9699235032773883,bias:-0.42967477914860386,loss:0.5741267707886694
Epoch:7,w1:0.9746176688933016,w2:0.9778915899179246,bias:-0.46793641497146393,loss:0.5705995858427959
Epoch:8,w1:0.9808896657598926,w2:0.9875548567224447,bias:-0.5026932067028589,loss:0.5676105756022634
Epoch:9,w1:0.9883199290518272,w2:0.9985796321060464,bias:-0.5344809929893508,loss:0.5650

In [46]:
coef,intercept

(array([[5.7122607],
        [1.9546393]], dtype=float32), array([-3.2028291], dtype=float32))